# Generated by Django 4.1.7 on 2023-03-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('expiry_date', models.DateField(null=True)),
                ('kumarg', models.CharField(max_length=255)),
            ],
        ),
    ]
