# Generated by Django 4.1.7 on 2023-04-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_medicine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
