# Generated by Django 4.1.7 on 2023-04-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_medicine_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='company',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='confirm_company',
            field=models.CharField(default='', max_length=255),
        ),
    ]
